### ISSUE TITLE
How do I login w/ username password?

### ISSUE THREAD

**Issue by NitroCipher** [yakyak/hangupsjs#101]
I can't seem to understand how the email/password login works. A little help?

**Comment by averissimo** [comment]
Here is the coffescript code to do so

The description on how to get the authorization token has been improved and is working as of today with the code below

```
Client = require './client'
Q      = require 'q'

# callback to get promise for creds using stdin. this in turn
# means the user must fire up their browser and get the
# requested token.
creds = -> auth:Client.authStdin

client = new Client()

# set more verbose logging
client.loglevel 'debug'

# receive chat message events
client.on 'chat_message', (ev) ->
    console.log ev
```

**Comment by averissimo** [comment]
1. Go to coffeescript.org
1. Click on try
1. Paste the coffescript code there

On the right you get the javascript compiled and you can use that
