### ISSUE TITLE
No longer connects

### ISSUE THREAD

**Issue by Riversiderepeat** [yakyak/hangupsjs#105]
Just started last night. Yakyak will no longer connect. What did Google do this time?

**Comment by averissimo** [comment]
I can successfully login to yakyak, can you try opening yakyak via a command line and see if you get an error?

**Comment by Riversiderepeat** [comment]
No error running from prompt. Window just opens and says connecting but never connects. Have tried deleting the installation and unpacking fresh. Still won't connect. 
Running on Windows 10. Was working perfectly fine until two nights ago when this suddenly started happening. No system changes or updates between normal functioning and this.

**Comment by Riversiderepeat** [comment]
No error running from prompt. Window just opens and says connecting but never connects. Have tried deleting the installation and unpacking fresh. Still won't connect. 
Running on Windows 10. Was working perfectly fine until two nights ago when this suddenly started happening. No system changes or updates between normal functioning and this.

**Comment by averissimo** [comment]
Current version should have this fixed.

**Comment by Riversiderepeat** [comment]
Won't even start now.

**Comment by Riversiderepeat** [comment]
All good now. Did a  Windows restart and thought it still wasn't starting but it was hiding in the system tray. Nice work! Thank you!
