### ISSUE TITLE
Send actions

### ISSUE THREAD

**Issue by timvdalen** [yakyak/hangupsjs#32]
In the Hangouts extension, it's possible to send (and receive) IRC-like actions using `/me`.

Since the mobile applications do not support this (neither sending nor receiving), I'm not sure if it's part of the protocol or done somewhere in the extension.
However, it seems like it has some sort of extra formatting, because simply sending '/me test' from a client that doesn't support actions does not result in an action on the Hangouts extension.

I would like to be able to send actions with hangupsjs

**Comment by algesten** [comment]
It will be a matter of figuring out what the underlying api calls are. It *may* simply be a specially formatted message. Or it may use a message that I haven't seen. You see those most easily by running the google hangups chat inside a web page (not plugin) and firing up the developer console and look at the traffic.

**Comment by timvdalen** [comment]
Okay, if I have the time I'll investigate and post results.

**Comment by timvdalen** [comment]
I checked it out and it seems to be something other than formatting, but it's definitely still a chat message.

Excerpts from protojson below.

Sending 'a':
```
[,[]
,[[[0,"a",[0,0,0,0]
]
]
,[]
]
]
```

Sending '_a_':
```
[,[]
,[[[0,"a",[0,1,0,0]
]
]
,[]
]
]
```

Sending '/me a':
```
[,[[4]
]
,[[[0,"/me a",[0,0,0,0]
]
]
,[]
]
]
```

Is there a way to make the Hangouts client in Gmail send json instead of protojson, so we know what we're looking at?

**Comment by timvdalen** [comment]
Regardless of what the 4 means, changing `[]` to `[[4]]` on this line: https://github.com/algesten/hangupsjs/blob/f7df998260eec3c052f80fb0ca39c733e3762e46/src/client.coffee#L261

Makes the library send actions.
The fun bit here is that the extension and client in Gmail won't trigger this unless you send a message starting with '/me' (which will show up as "<user> <msg>").
If you send a message with [[4]] that doesn't start with '/me', the hangouts clients will render this as just the message, leaving out the <user> part.

I'll leave the question of how to expose the functionality up to you, but seeing as you've kept pretty close to the API endpoints, it might be best to make the part of the message that controls this behaviour an optional argument to `sendchatmessage`.
What do you think?

**Comment by tdryer** [comment]
Added to hangups here: https://github.com/tdryer/hangups/commit/08c6852ea65f1adca1841bb6d4e0adca288f2e52 (thanks for the investigation @timvdalen!)

**Comment by algesten** [comment]
thanks @tdryer! now just need to find some time to add it to hangupsjs.
