### ISSUE TITLE
New lines in message disappears

### ISSUE THREAD

**Issue by KusioST** [yakyak/hangupsjs#67]
![yakyak](https://cloud.githubusercontent.com/assets/25057693/21850535/571830e4-d80b-11e6-9d7d-7f523d61d5cc.jpg)

On left message in YakYak on right oryginal on gmail.

**Comment by averissimo** [comment]
@KusioST can you report this on https://github.com/yakyak/yakyak instead? Hangupjs is the library that is used to connect with hangouts

**Comment by KusioST** [comment]
OK.
