### ISSUE TITLE
Browser support

### ISSUE THREAD

**Issue by Rudloff** [yakyak/hangupsjs#81]
Hello,

Is there any plan to have a version of this library that works in a browser context?
I guess the main issue is that it uses natives node APIs like `net` or `fs`.

Regards,

**Comment by lorenzos** [comment]
Native node APIs surely can be replaced by something else (i.e. XMLHttpRequest and local storage). But you can never work around same-origin policy, so I don't think it'll never be possible to port this in the browser.

**Comment by Rudloff** [comment]
I was thinking of using it in a Cordova app so CORS is not a problem here.

I tried using Browserify and a few shims and surprisingly the connect function seems to work (I haven't tested further) so I'm closing this.
