### ISSUE TITLE
Add withCredentials: 'include' to requests

### ISSUE THREAD

**Issue by Rudloff** [yakyak/hangupsjs#85]
Hello,

I'm using hangupsjs in a Cordova app so it basically runs in a browser context (but without CORS) and Browserify takes care of replacing Node APIs with similar Browser APIs.
The problem is that in the browser, requests don't send cookies unless you use the `withCredentials` option.

For example, this makes the auth work correctly:
```diff
diff --git a/src/auth.coffee b/src/auth.coffee
index 04adbbf..81ef517 100644
--- a/src/auth.coffee
+++ b/src/auth.coffee
@@ -188,6 +188,7 @@ module.exports = class Auth
                 jar: request.jar jarstore
                 proxy: opts.proxy
                 headers: headers
+                withCredentials: 'include'
         .then (res) ->
             return Q.reject NetworkError.forRes(res) unless res.statusCode == 200
             log.debug 'got uberauth'
@@ -200,6 +201,7 @@ module.exports = class Auth
                 uri: MERGE_SESSION
                 jar: request.jar jarstore
                 proxy: opts.proxy
+                withCredentials: 'include'
         .then (res) ->
             return Q.reject NetworkError.forRes(res) unless res.statusCode == 200
             log.debug 'request merge session 2/2'
@@ -209,6 +211,7 @@ module.exports = class Auth
                 jar: request.jar jarstore
                 proxy: opts.proxy
                 header: headers
+                withCredentials: 'include'
         .then (res) ->
             return Q.reject NetworkError.forRes(res) unless res.statusCode == 200
             log.debug 'got session cookies'
```

Is there a way to set this option globally or do I have to patch every request?

(This option is [specific to stream-http](https://github.com/jhiesey/stream-http#extra-features-compared-to-node). As far as I can tell, this option is simply ignored when using Node.)

**Comment by averissimo** [comment]
can you provide a pull request with this change so I can check if there is any conflict in Node (i.e. in Yakyak)

**Comment by Rudloff** [comment]
Fixed by https://github.com/yakyak/hangupsjs/commit/0f211abb22e235fc9c878df7d08ee4303ef58321.
