### ISSUE TITLE
Can't connect to hangouts anymore

### ISSUE THREAD

**Issue by guslanzetta1** [yakyak/hangupsjs#93]
Using Windows 10.

Have used Yakyak with this account for over a year now, no issues. Tried deleting app data, restarting, everything. Still stuck at the Connecting screen.

**Comment by bartoncasey** [comment]
This is due to a small change Google made to their HTML, which broke the parsing. 

More details (and a fix) here: https://github.com/yakyak/yakyak/issues/919#issuecomment-389866711

**Comment by guslanzetta1** [comment]
Thanks bartoncasey, it worked for me.

**Comment by lexoyo** [comment]
Hello
Can we expect a merge soon?

**Comment by rithvikvibhu** [comment]
Hey @Dodenis can you create a pull request for that commit of yours?

**Comment by averissimo** [comment]
@rithvikvibhu I believe commit 2bc46f179cfc97b87e5ebda6718008afd90fcec5 fixed this

can you check?

**Comment by rithvikvibhu** [comment]
Just tried it with the latest version (1.3.7) and it worked. Thanks @averissimo!

**Comment by averissimo** [comment]
On this one the credits are due in the community #104
